name: Action Workflow

on:
  push:
    branches: 
      - master
      - 'feature/*' # matches anything starteing with feature/{{something}}.
      - '!feature/featC' # this will ignore this branch.
    tags: # or tags-ignore; can't be used together.
      - v1.*
    paths: # or paths-ignore; can't be used together.
      - '**.js' # this will match any js file in our repo.

  # schedule:
  #   - cron: "*/5 * * * *"
  #   - cron: "*/6 * * * *"
  # repository_dispatch:
  #   types: [build]
  # pull_request:
  #   types:
  #     - closed
  #     - assigned
  #     - opened
  #     - reopened

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Payload
        run: |
          echo ${{ github.event.client_payload.env }}
          echo ${{ github.event.client_payload.name }}
      - name: List Files
        run: |
          pwd 
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: List Files after Checkout
        run: |
          pwd 
          ls -la
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Chi
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"