name: Update branch

permissions:
  checks: write
  id-token: write
  pull-requests: write
  contents: write
  issues: write

env: 
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  # pull_request:
  #   types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  update-branch:
    name: Merge master into PR
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - run: |
          gh pr checkout ${{github.event.issue.number}}

      - name: Log stuff
        run: |
          ls -a

      # - name: Check for comment "update branch"
      #   id: check-comment
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const comments = await github.rest.issues.listComments({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: context.issue.number,
      #       });
            
      #       console.log('comments', comments)
      #       for (const comment of comments.data) {
      #           if (comment.body.toLowerCase().includes("update master")) {
      #             return true;
      #           }
      #         }
      #       return false;

      - name: Merge master into PR branch
        if: ${{ github.event.comment.body == 'update branch' }}
        run: |
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch 
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull

          ls -a
          git checkout ${{github.head_ref}}
          git commit -am "Merge branch 'master' into $GITHUB_REF"
          git merge
          git push