name: Merge master into PR

permissions:
  checks: write
  id-token: write
  pull-requests: write
  contents: write
  issues: write

env: 
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

on:
  # pull_request:
  #   types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  update-branch:
    name: Merge master
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      # - name: Log stuff
      #   run: |
      #     ls -a
      #     echo $GITHUB_REF
      #     echo ${{github.base_ref}}
      #     echo ${{github.ref}}

      # - name: Check for comment "update branch"
      #   id: check-comment
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const comments = await github.rest.issues.listComments({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: context.issue.number,
      #       });
            
      #       console.log('comments', comments)
      #       for (const comment of comments.data) {
      #           if (comment.body.toLowerCase().includes("update master")) {
      #             return true;
      #           }
      #         }
      #       return false;

      - name: Merge master into PR branch
        if: ${{ github.event.comment.body == 'update branch' }}
        run: |
          echo default branch: $DEFAULT_BRANCH
          echo github actor: ${GITHUB_ACTOR}
          echo head ref: ${GITHUB_HEAD_REF}
          echo base ref: ${GITHUB_BASE_REF}
          echo ref name: ${GITHUB_REF_NAME}


          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git status
          git pull
          git checkout "$DEFAULT_BRANCH"
          git status
          git checkout "$GITHUB_HEAD_REF"
          git merge "$DEFAULT_BRANCH" --no-edit  -m "Merge branch 'master' into $GITHUB_REF"
          git push
          git status
